"""New Migration

Revision ID: 99138376b219
Revises: 2b0529c6a90e
Create Date: 2022-07-16 07:01:56.742355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99138376b219'
down_revision = '2b0529c6a90e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
